/**
 * Scans Live preview.tsx files and Experimental idea sources, then writes
 * generated lazy-import maps (Bun has no Vite import.meta.glob).
 */
import { Glob } from "bun";
import { mkdir } from "node:fs/promises";
import path from "node:path";

const ROOT = path.join(import.meta.dir, "..");
const LIVE = path.join(ROOT, "src", "live");
const IDEAS = path.join(ROOT, "src", "experimental", "ideas");
const LIVE_OUT = path.join(ROOT, "src", "lib", "playground.gen.ts");
const IDEAS_OUT = path.join(ROOT, "src", "experimental", "ideas.gen.ts");
const IDEA_NAME_RE = /^[A-Za-z][A-Za-z0-9]*$/;

export async function syncPlaygroundRegistry(): Promise<string[]> {
  const glob = new Glob("**/preview.tsx");
  const slugs: string[] = [];

  for await (const file of glob.scan({ cwd: LIVE, onlyFiles: true })) {
    const slug = file.replace(/\/preview\.tsx$/, "").replace(/\\/g, "/");
    slugs.push(slug);
  }

  slugs.sort((a, b) => a.localeCompare(b));

  const moduleLines = slugs.map(slug => {
    const importPath = `../live/${slug}/preview.tsx`;
    return `  ${JSON.stringify(slug)}: () => import(${JSON.stringify(importPath)}),`;
  });

  const source = `/* eslint-disable */
// Auto-generated by scripts/sync-playground.ts — do not edit by hand.
import type { PreviewModule } from "./types";

export const previewModules: Record<string, () => Promise<PreviewModule>> = {
${moduleLines.join("\n")}
};
`;

  await mkdir(path.dirname(LIVE_OUT), { recursive: true });
  await Bun.write(LIVE_OUT, source);
  return slugs;
}

export async function syncIdeaRegistry(): Promise<string[]> {
  const glob = new Glob("*/source.tsx");
  const names: string[] = [];

  for await (const file of glob.scan({ cwd: IDEAS, onlyFiles: true })) {
    const name = file.replace(/\/source\.tsx$/, "").replace(/\\/g, "/");
    if (!name.includes("/") && IDEA_NAME_RE.test(name)) names.push(name);
  }

  names.sort((a, b) => a.localeCompare(b));

  const moduleLines = names.map(name => {
    const importPath = `./ideas/${name}/source.tsx`;
    return `  ${JSON.stringify(name)}: () => import(${JSON.stringify(importPath)}),`;
  });

  const source = `/* eslint-disable */
// Auto-generated by scripts/sync-playground.ts — do not edit by hand.
import type { ComponentType } from "react";

export type IdeaExample = ComponentType<{
  sliders?: Record<string, number>;
  progress?: number;
}>;

export const ideaModules: Record<
  string,
  () => Promise<{ Example?: IdeaExample }>
> = {
${moduleLines.join("\n")}
};
`;

  await mkdir(path.dirname(IDEAS_OUT), { recursive: true });
  await Bun.write(IDEAS_OUT, source);
  return names;
}

if (import.meta.main) {
  const slugs = await syncPlaygroundRegistry();
  const ideas = await syncIdeaRegistry();
  console.log(`Synced ${slugs.length} Live entries:`);
  for (const slug of slugs) {
    console.log(`  - ${slug}`);
  }
  console.log(`Synced ${ideas.length} Experimental ideas:`);
  for (const name of ideas) {
    console.log(`  - ${name}`);
  }
}
