/**
 * Scans Live preview.tsx files and writes src/lib/playground.gen.ts
 * so the client bundle gets explicit lazy imports (Bun-friendly auto-discovery).
 */
import { Glob } from "bun";
import { mkdir } from "node:fs/promises";
import path from "node:path";
import type { PlaygroundStatus } from "../src/lib/types";

const ROOT = path.join(import.meta.dir, "..");
const LIVE = path.join(ROOT, "src", "live");
const OUT = path.join(ROOT, "src", "lib", "playground.gen.ts");

/** Read preview source and detect `status: "experimental"` in meta. Default live. */
export function statusFromPreviewSource(source: string): PlaygroundStatus {
  if (/status\s*:\s*["']experimental["']/.test(source)) {
    return "experimental";
  }
  return "live";
}

export async function syncPlaygroundRegistry(): Promise<
  { slug: string; status: PlaygroundStatus }[]
> {
  const glob = new Glob("**/preview.tsx");
  const entries: { slug: string; status: PlaygroundStatus }[] = [];

  for await (const file of glob.scan({ cwd: LIVE, onlyFiles: true })) {
    const slug = file.replace(/\/preview\.tsx$/, "").replace(/\\/g, "/");
    const absolute = path.join(LIVE, file);
    const source = await Bun.file(absolute).text();
    entries.push({
      slug,
      status: statusFromPreviewSource(source),
    });
  }

  entries.sort((a, b) => a.slug.localeCompare(b.slug));

  const moduleLines = entries.map(({ slug }) => {
    const importPath = `../live/${slug}/preview.tsx`;
    return `  ${JSON.stringify(slug)}: () => import(${JSON.stringify(importPath)}),`;
  });

  const statusLines = entries.map(
    ({ slug, status }) => `  ${JSON.stringify(slug)}: ${JSON.stringify(status)},`,
  );

  const source = `/* eslint-disable */
// Auto-generated by scripts/sync-playground.ts — do not edit by hand.
import type { PlaygroundStatus, PreviewModule } from "./types";

export const previewModules: Record<string, () => Promise<PreviewModule>> = {
${moduleLines.join("\n")}
};

export const previewStatuses: Record<string, PlaygroundStatus> = {
${statusLines.join("\n")}
};
`;

  await mkdir(path.dirname(OUT), { recursive: true });
  await Bun.write(OUT, source);
  return entries;
}

if (import.meta.main) {
  const entries = await syncPlaygroundRegistry();
  console.log(`Synced ${entries.length} Live entries:`);
  for (const { slug, status } of entries) {
    console.log(`  - ${slug} (${status})`);
  }
}
