/* eslint-disable */
// Auto-generated by scripts/sync-playground.ts — do not edit by hand.
import type { ComponentType } from "react";

export type IdeaExample = ComponentType<{
  sliders?: Record<string, number>;
  progress?: number;
}>;

export const ideaModules: Record<
  string,
  () => Promise<{ Example?: IdeaExample }>
> = {
  "BirdTwo": () => import("./ideas/BirdTwo/source.tsx"),
  "LightDispersion": () => import("./ideas/LightDispersion/source.tsx"),
};
