/**
 * Scans playground preview.tsx files and writes src/lib/playground.gen.ts
 * so the client bundle gets explicit lazy imports (Bun-friendly auto-discovery).
 */
import { Glob } from "bun";
import { mkdir } from "node:fs/promises";
import path from "node:path";

const ROOT = path.join(import.meta.dir, "..");
const PLAYGROUND = path.join(ROOT, "src", "playground");
const OUT = path.join(ROOT, "src", "lib", "playground.gen.ts");

export async function syncPlaygroundRegistry(): Promise<string[]> {
  const glob = new Glob("**/preview.tsx");
  const slugs: string[] = [];

  for await (const file of glob.scan({ cwd: PLAYGROUND, onlyFiles: true })) {
    const slug = file.replace(/\/preview\.tsx$/, "").replace(/\\/g, "/");
    slugs.push(slug);
  }

  slugs.sort((a, b) => a.localeCompare(b));

  const lines = slugs.map(slug => {
    const importPath = `../playground/${slug}/preview.tsx`;
    return `  ${JSON.stringify(slug)}: () => import(${JSON.stringify(importPath)}),`;
  });

  const source = `/* eslint-disable */
// Auto-generated by scripts/sync-playground.ts — do not edit by hand.
import type { PreviewModule } from "./types";

export const previewModules: Record<string, () => Promise<PreviewModule>> = {
${lines.join("\n")}
};
`;

  await mkdir(path.dirname(OUT), { recursive: true });
  await Bun.write(OUT, source);
  return slugs;
}

if (import.meta.main) {
  const slugs = await syncPlaygroundRegistry();
  console.log(`Synced ${slugs.length} playground experiment(s):`);
  for (const slug of slugs) console.log(`  - ${slug}`);
}
