/* eslint-disable */
// Auto-generated by scripts/sync-playground.ts — do not edit by hand.
import type { PreviewModule } from "./types";

export const previewModules: Record<string, () => Promise<PreviewModule>> = {
  "buttons/PrimaryButton": () => import("../live/buttons/PrimaryButton/preview.tsx"),
  "shells/ConfigurableShell": () => import("../live/shells/ConfigurableShell/preview.tsx"),
};
