/* eslint-disable */
// Auto-generated by scripts/sync-playground.ts — do not edit by hand.
import type { PlaygroundStatus, PreviewModule } from "./types";

export const previewModules: Record<string, () => Promise<PreviewModule>> = {
  "buttons/PrimaryButton": () => import("../playground/buttons/PrimaryButton/preview.tsx"),
  "shells/ConfigurableShell": () => import("../playground/shells/ConfigurableShell/preview.tsx"),
};

export const previewStatuses: Record<string, PlaygroundStatus> = {
  "buttons/PrimaryButton": "live",
  "shells/ConfigurableShell": "live",
};
